/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bowoon_android_mylibrary_Practice */

#ifndef _Included_com_bowoon_android_mylibrary_Practice
#define _Included_com_bowoon_android_mylibrary_Practice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bowoon_android_mylibrary_Practice
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bowoon_android_mylibrary_Practice_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
