/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bowoon_android_jni_Constant */

#ifndef _Included_com_bowoon_android_jni_Constant
#define _Included_com_bowoon_android_jni_Constant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bowoon_android_jni_Constant
 * Method:    getAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bowoon_android_jni_Constant_getAddress
  (JNIEnv *, jclass);

/*
 * Class:     com_bowoon_android_jni_Constant
 * Method:    getPort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bowoon_android_jni_Constant_getPort
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
