/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bowoon_android_jni_JNILZWEncoder */

#ifndef _Included_com_bowoon_android_jni_JNILZWEncoder
#define _Included_com_bowoon_android_jni_JNILZWEncoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bowoon_android_jni_JNILZWEncoder_EOF
#define com_bowoon_android_jni_JNILZWEncoder_EOF -1L
#undef com_bowoon_android_jni_JNILZWEncoder_BITS
#define com_bowoon_android_jni_JNILZWEncoder_BITS 12L
#undef com_bowoon_android_jni_JNILZWEncoder_HSIZE
#define com_bowoon_android_jni_JNILZWEncoder_HSIZE 5003L
/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    char_out
 * Signature: (BLjava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_char_1out
  (JNIEnv *, jobject, jbyte, jobject);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    cl_block
 * Signature: (Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_cl_1block
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    cl_hash
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_cl_1hash
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    compress
 * Signature: (ILjava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_compress
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    encode
 * Signature: (Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_encode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    flush_char
 * Signature: (Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_flush_1char
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    MAXCODE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_MAXCODE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    nextPixel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_nextPixel
  (JNIEnv *, jobject);

/*
 * Class:     com_bowoon_android_jni_JNILZWEncoder
 * Method:    output
 * Signature: (ILjava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_bowoon_android_jni_JNILZWEncoder_output
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
